### ISSUE TITLE
String format error with GCC 5 [-Werror=format-security]

### ISSUE THREAD

**Issue by akien-mga** [Andrettin/Wyrmgus#101]
Fails to build with GCC 5 and wyrmgus 2.4.0:
```
[ 78%] Building CXX object CMakeFiles/stratagus.dir/src/stratagus/script_player.cpp.o
/bin/c++   -DHAVE_GETOPT -DHAVE_STRCASESTR -DHAVE_STRNLEN -DPIXMAPS=\"/usr/share/pixmaps\" -DUSE_LINUX -DUSE_MIKMOD -DUSE_OAML -DUSE_OPENGL -DUSE_THEORA -DUSE_VORBIS -DUSE_X11 -DUSE_ZLIB -I/home/akien/Mageia/Checkout/wyrmsun/BUILD/Wyrmgus-2.4.0/src/include -I/home/akien/Mageia/Checkout/wyrmsun/BUILD/Wyrmgus-2.4.0/src/guichan/include -I/home/akien/Mageia/Checkout/wyrmsun/BUILD/Wyrmgus-2.4.0/src/guichan/include/guichan -I/home/akien/Mageia/Checkout/wyrmsun/BUILD/Wyrmgus-2.4.0/src/xbrz/include -I/home/akien/Mageia/Checkout/wyrmsun/BUILD/Wyrmgus-2.4.0/build -I/usr/include/. -I/usr/include/SDL -I/home/akien/Mageia/Checkout/wyrmsun/BUILD/Wyrmgus-2.4.0/src/oaml/include  -std=c++11 -O2 -g -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4  -fsigned-char -std=c++11 -DNDEBUG   -o CMakeFiles/stratagus.dir/src/stratagus/script_player.cpp.o -c /home/akien/Mageia/Checkout/wyrmsun/BUILD/Wyrmgus-2.4.0/src/stratagus/script_player.cpp
/home/akien/Mageia/Checkout/wyrmsun/BUILD/Wyrmgus-2.4.0/src/stratagus/script_player.cpp: In function 'int CclSetThisPlayer(lua_State*)':
/home/akien/Mageia/Checkout/wyrmsun/BUILD/Wyrmgus-2.4.0/src/stratagus/script_player.cpp:505:69: error: format not a string literal and no format arguments [-Werror=format-security]
     SetObjective(ThisPlayer->CurrentQuests[i]->Objectives[j].c_str());
                                                                     ^
```

Also, a format-related warning:
```
[ 46%] Building CXX object CMakeFiles/stratagus.dir/src/map/tileset.cpp.o
/bin/c++   -DHAVE_GETOPT -DHAVE_STRCASESTR -DHAVE_STRNLEN -DPIXMAPS=\"/usr/share/pixmaps\" -DUSE_LINUX -DUSE_MIKMOD -DUSE_OAML -DUSE_OPENGL -DUSE_THEORA -DUSE_VORBIS -DUSE_X11 -DUSE_ZLIB -I/home/akien/Mageia/Checkout/wyrmsun/BUILD/Wyrmgus-2.4.0/src/include -I/home/akien/Mageia/Checkout/wyrmsun/BUILD/Wyrmgus-2.4.0/src/guichan/include -I/home/akien/Mageia/Checkout/wyrmsun/BUILD/Wyrmgus-2.4.0/src/guichan/include/guichan -I/home/akien/Mageia/Checkout/wyrmsun/BUILD/Wyrmgus-2.4.0/src/xbrz/include -I/home/akien/Mageia/Checkout/wyrmsun/BUILD/Wyrmgus-2.4.0/build -I/usr/include/. -I/usr/include/SDL -I/home/akien/Mageia/Checkout/wyrmsun/BUILD/Wyrmgus-2.4.0/src/oaml/include  -std=c++11 -O2 -g -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4  -fsigned-char -std=c++11 -DNDEBUG   -o CMakeFiles/stratagus.dir/src/map/tileset.cpp.o -c /home/akien/Mageia/Checkout/wyrmsun/BUILD/Wyrmgus-2.4.0/src/map/tileset.cpp
In file included from /home/akien/Mageia/Checkout/wyrmsun/BUILD/Wyrmgus-2.4.0/src/map/script_map.cpp:41:0:
/home/akien/Mageia/Checkout/wyrmsun/BUILD/Wyrmgus-2.4.0/src/map/script_map.cpp: In function 'int CclDefineTerrainType(lua_State*)':
/home/akien/Mageia/Checkout/wyrmsun/BUILD/Wyrmgus-2.4.0/src/include/script.h:80:23: warning: format '%s' expects a matching 'char*' argument [-Wformat=]
   fprintf(stdout, args); \
                       ^
/home/akien/Mageia/Checkout/wyrmsun/BUILD/Wyrmgus-2.4.0/src/map/script_map.cpp:1198:6: note: in expansion of macro 'LuaError'
      LuaError(l, "Flag \"%s\" doesn't exist.");
      ^
```

**Comment by Andrettin** [comment]
Thanks for letting me know :)

Should be fixed now:
https://github.com/Andrettin/Wyrmgus/commit/bd7b68676d1a51a604c57deb0546958fd60bc9c9

**Comment by akien-mga** [comment]
Fix confirmed, thanks :)
