### ISSUE TITLE
fails to build with boost 1.87.0

### ISSUE THREAD

**Issue by david-geiger** [Andrettin/Wyrmgus#195]
Hi,

On Mageia Cauldron wyrmgus fails to build with latest boost 1.87.0 with the following build issue:

> /home/pterjan/rpmbuild/BUILD/wyrmsun-5.3.6-build/Wyrmgus-5.3.6/src/util/event_loop.cpp:97:15: error: 'boost::asio::steady_timer' {aka 'class boost::asio::basic_waitable_timer<std::chrono::_V2::steady_clock>'} has no member named 'expires_from_now'
   97 |         timer.expires_from_now(std::chrono::milliseconds(ms));
      |               ^~~~~~~~~~~~~~~~
In file included from /home/pterjan/rpmbuild/BUILD/wyrmsun-5.3.6-build/Wyrmgus-5.3.6/build/CMakeFiles/wyrmgus.dir/Unity/unity_util_cxx.cxx:64:
/home/pterjan/rpmbuild/BUILD/wyrmsun-5.3.6-build/Wyrmgus-5.3.6/src/util/thread_pool.cpp: In member function 'boost::asio::awaitable<void> wyrmgus::thread_pool::await_ms(uint64_t)':
/home/pterjan/rpmbuild/BUILD/wyrmsun-5.3.6-build/Wyrmgus-5.3.6/src/util/thread_pool.cpp:87:15: error: 'boost::asio::steady_timer' {aka 'class boost::asio::basic_waitable_timer<std::chrono::_V2::steady_clock>'} has no member named 'expires_from_now'
   87 |         timer.expires_from_now(std::chrono::milliseconds(ms));
      |               ^~~~~~~~~~~~~~~~
In file included from /home/pterjan/rpmbuild/BUILD/wyrmsun-5.3.6-build/Wyrmgus-5.3.6/build/CMakeFiles/wyrmgus.dir/Unity/unity_network_cxx.cxx:34:
/home/pterjan/rpmbuild/BUILD/wyrmsun-5.3.6-build/Wyrmgus-5.3.6/src/network/netsockets.cpp: In static member function 'static boost::asio::awaitable<void> CHost::from_host_name_and_port(CHost&, const std::string_view&, uint16_t)':
/home/pterjan/rpmbuild/BUILD/wyrmsun-5.3.6-build/Wyrmgus-5.3.6/src/network/netsockets.cpp:47:41: error: 'iterator' is not a member of 'boost::asio::ip::tcp::resolver' {aka 'boost::asio::ip::basic_resolver<boost::asio::ip::tcp>'}
   47 |         boost::asio::ip::tcp::resolver::iterator it = co_await resolver.async_resolve(host_name, std::to_string(port), boost::asio::use_awaitable);
      |                                         ^~~~~~~~
/home/pterjan/rpmbuild/BUILD/wyrmsun-5.3.6-build/Wyrmgus-5.3.6/src/network/netsockets.cpp:49:41: error: 'iterator' is not a member of 'boost::asio::ip::tcp::resolver' {aka 'boost::asio::ip::basic_resolver<boost::asio::ip::tcp>'}
   49 |         boost::asio::ip::tcp::resolver::iterator it_end;
      |                                         ^~~~~~~~
/home/pterjan/rpmbuild/BUILD/wyrmsun-5.3.6-build/Wyrmgus-5.3.6/src/network/netsockets.cpp:51:16: error: 'it' was not declared in this scope; did you mean 'ip'?
   51 |         for (; it != it_end; ++it) {
      |                ^~
      |                ip
/home/pterjan/rpmbuild/BUILD/wyrmsun-5.3.6-build/Wyrmgus-5.3.6/src/network/netsockets.cpp:51:22: error: 'it_end' was not declared in this scope; did you mean 'va_end'?
   51 |         for (; it != it_end; ++it) {
      |                      ^~~~~~
      |                      va_end

Attached full build log:

[build.x86_64.0.20250210135851.log](https://github.com/user-attachments/files/18809006/build.x86_64.0.20250210135851.log)
